<?php
namespace Admin\Controller;

use Think\Controller;
use Think\Model;

class ArticleController extends CommonController
{

	function dolist()
	{
		$ArticleModel = D('Article');
		$articleList = $ArticleModel->where('is_delete = 0')->select();
		$this->articleList = $articleList;
		$this->display('Article/list');
	}

	function update()
	{
		$issubmit = I('get.issubmit');
		$isdelete = I('get.isdelete');
		$id = I('get.id');
		$article = D("Article");
		// 文章标签列表
		$Tags = D('Tags');
		$articleTags = array();
		if ($id) {
			$article->where('id=' . $id)->find();
			$articleTags = explode(',', $article->tags);
		}
		if ($issubmit) {
			$data = I('', '', false);
			if ($isdelete && isset($id)) {
				$data['is_delete'] = 1;
				$data['id'] = $id;
				$article->create($data);
				if ($article->save()) {
					$this->redirect('Article/dolist');
				} else {
					$article->getError();
				}
			}
			$data['tags'] = implode(',', $data['tags']);
			if ($id) {
				// 更新
				$data['id'] = $id;
				$article->create($data);
				if ($article->save()) {
					$this->redirect('Article/dolist');
				} else {
					$article->getError();
				}
			} else {
				$article->create($data);
				$result = $article->add();
				if ($result) {
					$this->redirect('Article/dolist');
				} else {
					$article->getError();
				}
			}

		}
		$this->assign('article', $article);
		$this->assign('tagsList', $Tags->select());
		$this->assign('articleTags', $articleTags);
		$this->display();
	}

	function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->navType = 'article';
		$this->navLeft = "article";
	}
}