<?php
namespace Admin\Controller;

use Think\Controller;
use Think\Model;

class TagsController extends CommonController
{
	public function dolist()
	{
		$tags = D('tags');
		$this->tagsList = $tags->select();
		$this->display('Tags/list');
	}

	function update()
	{
		$issubmit = I('get.issubmit');
		$isdelete = I('get.isdelete');
		$id = I('get.id');
		$tags = D("Tags");
		if ($id) {
			$tags->where('id=' . $id)->find();
		}
		if ($issubmit) {
			$data = I();
			if ($id) {
				$data['id'] = $id;
				if ($isdelete) {
					// 删除
					$tags->delete($id);
					$this->redirect('Tags/dolist');
				}
				// 更新
				$tags->create($data);
				if ($tags->save()) {
					$this->redirect('Tags/dolist');
				} else {
					$tags->getError();
				}
			} else {
				// 新增
				$tags->create($data);
				$result = $tags->add();
				if ($result) {
					$this->redirect('Tags/dolist');
				} else {
					$tags->getError();
				}
			}
		}
		$this->assign('tags', $tags);
		$this->display();
	}

	function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->navType = 'article';
		$this->navLeft = 'tags';
	}
}